package std.go.os;

@:go.Type({ name: "os", instanceName: "os.os", imports: ["os"] })
extern class Os {

    static function chdir(dir: String): go.Error;
    static function chmod(name: String, mode: std.go.os.FileMode): go.Error;
    static function chown(name: String, uid: Int, gid: Int): go.Error;
    static function chtimes(name: String, atime: go.time.Time, mtime: go.time.Time): go.Error;
    static function clearenv(): Void;
    static function copyFS(dir: String, fsys: Dynamic): go.Error;
    static function create(name: String): go.Result<go.Pointer<std.go.os.File>>;
    static function createTemp(dir: String, pattern: String): go.Result<go.Pointer<std.go.os.File>>;
    static function dirFS(dir: String): Dynamic;
    static function environ(): go.Slice<String>;
    static function executable(): go.Result<String>;
    static function exit(code: Int): Void;
    static function expand(s: String, mapping: (p0: String) -> String): String;
    static function expandEnv(s: String): String;
    static function findProcess(pid: Int): go.Result<go.Pointer<std.go.os.Process>>;
    static function getegid(): Int;
    static function getenv(key: String): String;
    static function geteuid(): Int;
    static function getgid(): Int;
    static function getgroups(): go.Result<go.Slice<Int>>;
    static function getpagesize(): Int;
    static function getpid(): Int;
    static function getppid(): Int;
    static function getuid(): Int;
    static function getwd(): go.Result<String>;
    static function hostname(): go.Result<String>;
    static function isExist(err: go.Error): Bool;
    static function isNotExist(err: go.Error): Bool;
    static function isPathSeparator(c: go.UInt8): Bool;
    static function isPermission(err: go.Error): Bool;
    static function isTimeout(err: go.Error): Bool;
    static function lchown(name: String, uid: Int, gid: Int): go.Error;
    static function link(oldname: String, newname: String): go.Error;
    @:go.Tuple("p0", "p1") static function lookupEnv(key: String): go.Tuple<{ p0: String, p1: Bool }>;
    static function lstat(name: String): go.Result<std.go.os.FileInfo>;
    static function mkdir(name: String, perm: std.go.os.FileMode): go.Error;
    static function mkdirAll(path: String, perm: std.go.os.FileMode): go.Error;
    static function mkdirTemp(dir: String, pattern: String): go.Result<String>;
    static function newFile(fd: go.UIntPtr, name: String): go.Pointer<std.go.os.File>;
    static function newSyscallError(syscall: String, err: go.Error): go.Error;
    static function open(name: String): go.Result<go.Pointer<std.go.os.File>>;
    static function openFile(name: String, flag: Int, perm: std.go.os.FileMode): go.Result<go.Pointer<std.go.os.File>>;
    static function openInRoot(dir: String, name: String): go.Result<go.Pointer<std.go.os.File>>;
    static function openRoot(name: String): go.Result<go.Pointer<std.go.os.Root>>;
    @:go.Tuple("r", "w", "err") static function pipe(): go.Tuple<{ r: go.Pointer<std.go.os.File>, w: go.Pointer<std.go.os.File>, err: go.Error }>;
    static function readDir(name: String): go.Result<go.Slice<std.go.os.DirEntry>>;
    static function readFile(name: String): go.Result<go.Slice<go.Byte>>;
    static function readlink(name: String): go.Result<String>;
    static function remove(name: String): go.Error;
    static function removeAll(path: String): go.Error;
    static function rename(oldpath: String, newpath: String): go.Error;
    static function sameFile(fi1: std.go.os.FileInfo, fi2: std.go.os.FileInfo): Bool;
    static function setenv(key: String, value: String): go.Error;
    static function startProcess(name: String, argv: go.Slice<String>, attr: go.Pointer<std.go.os.ProcAttr>): go.Result<go.Pointer<std.go.os.Process>>;
    static function stat(name: String): go.Result<std.go.os.FileInfo>;
    static function symlink(oldname: String, newname: String): go.Error;
    static function tempDir(): String;
    static function truncate(name: String, size: go.Int64): go.Error;
    static function unsetenv(key: String): go.Error;
    static function userCacheDir(): go.Result<String>;
    static function userConfigDir(): go.Result<String>;
    static function userHomeDir(): go.Result<String>;
    static function writeFile(name: String, data: go.Slice<go.Byte>, perm: std.go.os.FileMode): go.Error;

}